name: Deploy Morrischem Theme to Hetzner

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync Files to Hetzner Server
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: FTP Deploy to Hetzner
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./morrischem-industrial-clean/
        server-dir: /public_html/Morrischem/wp-content/themes/morrischem-industrial-clean/
        protocol: ftps
        security: loose
